name: Desktop and Mobile Builds (Linux, macOS, Windows, AAB, APK, IPA)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11.0
  FLET_CLI_VERSION: 0.25.2
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Build for Linux
        run: |
          flet build linux --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: linux-build
          path: build/linux
          if-no-files-found: warn

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==$env:FLET_CLI_VERSION

      - name: Build for Windows
        run: |
          flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windows-build
          path: build/windows
          if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Build for macOS
        run: |
          flet build macos --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: macos-build
          path: build/macos
          if-no-files-found: warn

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Build APK
        run: |
          flet build apk --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

      - name: Upload APK Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: apk-build
          path: build/apk
          if-no-files-found: warn

  build-aab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Build AAB
        run: |
          flet build aab --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

      - name: Upload AAB Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: aab-build
          path: build/aab
          if-no-files-found: warn

  build-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Build IPA
        run: |
          flet build ipa --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

      - name: Upload IPA Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ipa-build
          path: build/ipa
          if-no-files-found: warn
